server:
  port: 80
spring:
  redis:
    database: 0
    host: 39.107.26.81
    port: 6379
    #password: "!QAZ2wsx"
    #host: 127.0.0.1
    #port: 6379
#logging:
#  level:
#    org.springframework: DEBUG
